<br /><br />
<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>index</b></p>
</div>

<?php



$url = "https://www.youtube.com/watch?v=TlGFWCgoMSw";
$c = curl_init($url);
curl_setopt($c, CURLOPT_RETURNTRANSFER, TRUE);
$html = curl_exec($c);
if (curl_error($c))
    die(curl_error($c));

// Get the status code
$status = curl_getinfo($c, CURLINFO_HTTP_CODE);

curl_close($c);
var_dump($html);
exit();